<template>
  <section>
    <h2>Notes</h2>

    <div id="scroll-behaviour">
      <h3>Scroll behaviour</h3>
      <p>If you need to jump directly to a particular anchor tag which is
         a children of a router view, you need to modify
         <code>scrollBehaviour</code> function as follows:</p>

      <pre v-highlightjs><code class="javascript">
      new VueRouter({
        scrollBehavior(to, from, savedPosition) {
          if (to.hash) {
            return { selector: to.hash }
          } else {
            return { x: 0, y: 0}
          }
        },
      });
      </code></pre>

      <div class="additional">
        Note on troubleshooting:
        Scroll stopped working in the moment I implemented two columns with two scrollbars
        layout when developing this website. I found out it is probably caused by setting
        both <code>&lt;html&gt;</code> and <code>&lt;body&gt;</code> height to 100%.
        The only workaround I found out so far is to use <code>scrollToView()</code>
        which seems to work under all circumstances.
        If you face this issue in your project, this
        <a href="https://github.com/vuejs/vue-router/issues/1459" target="_blank">issue</a>
        could help you or you can check the <a href="https://github.com/MisRob/doc-vue-tree-navigation/blob/master/src/main.js#L38" target="_blank">workaround</a>
        in this website repository. If you find better solution, let me know ;)
      </div>
    </div>
    
    <div id="styling">
      <h3>Styling</h3>
      <ul>
        <li>All hyperlinks generated by vue-router are assigned <code>router-link</code> class</li>
        <li>All closed levels (<code>&lt;ul&gt;</code> elements) are assigned <code>closed</code> class</li>
      </ul>
    </div>
  </section>
</template>

<style scoped>
#styling {
  margin-top: 30px;
}
</style>
